# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

# CodeRabbit is an AI-powered code reviewer that cuts review time and bugs in half

language: en-US
early_access: false
reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  path_instructions:
    - path: '**/*.{ts,tsx,js,jsx}'
      instructions: |
        Review the TypeScript/JavaScript code for:
        - Type safety and proper typing
        - React best practices (for React components)
        - Performance considerations
        - Code organization and maintainability
        - Security best practices
        - Error handling patterns
    - path: 'packages/**/*'
      instructions: |
        Review package-specific code for:
        - Proper package boundaries
        - Clean API design
        - Documentation quality
        - Testing coverage
    - path: 'apps/**/*'
      instructions: |
        Review application code for:
        - User experience considerations
        - Integration patterns
        - Configuration management
        - Deployment readiness
  auto_review:
    enabled: true
    ignore_title_keywords:
      - WIP
      - DO NOT MERGE
      - DRAFT
      - '[skip ci]'
    drafts: false
chat:
  auto_reply: true
  background_context: |
    This is a monorepo project using:
    - pnpm workspace
    - TypeScript
    - ESLint with @antfu/eslint-config
    - Multiple packages and applications
    - Focus on clean architecture and type safety