/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaticRouteRouteImport } from './routes/_static/route'
import { Route as StaticIndexRouteImport } from './routes/_static/index'

const StaticRouteRoute = StaticRouteRouteImport.update({
  id: '/_static',
  getParentRoute: () => rootRouteImport,
} as any)
const StaticIndexRoute = StaticIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaticRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof StaticIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof StaticIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_static': typeof StaticRouteRouteWithChildren
  '/_static/': typeof StaticIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/_static' | '/_static/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StaticRouteRoute: typeof StaticRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_static': {
      id: '/_static'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof StaticRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_static/': {
      id: '/_static/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StaticIndexRouteImport
      parentRoute: typeof StaticRouteRoute
    }
  }
}

interface StaticRouteRouteChildren {
  StaticIndexRoute: typeof StaticIndexRoute
}

const StaticRouteRouteChildren: StaticRouteRouteChildren = {
  StaticIndexRoute: StaticIndexRoute,
}

const StaticRouteRouteWithChildren = StaticRouteRoute._addFileChildren(
  StaticRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  StaticRouteRoute: StaticRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
